spring:
  cloud:
    config:
      server:
        git:
          uri: 'https://github.com/elRafa85/ConfigData/'
      native:
        searchLocations: classpath:offline-repository/
server:
  port: 8001
logging:
  level: debug
